### ISSUE TITLE
你好，李老师。可以对多类别数据集比如Landsat-SCD进行训练吗

### ISSUE THREAD

**Issue by wangqingl** [likyoo/BAN#1]

**Comment by likyoo** [comment]
可以的，因为Landsat-SCD没有官方的划分，所以没有把config传上去~ 可以根据其他配置文件写一下，应该不复杂的哈

**Comment by wangqingl** [comment]
> 可以的，因为Landsat-SCD没有官方的划分，所以没有把config传上去~ 可以根据其他配置文件写一下，应该不复杂的哈
好的谢谢，没有官方划分是什么意思呀，我之前那下载他的数据集，label标签是10个变化类别呢，我用程序读取他的像素值，他用的0-9十个数字表示的类别
![image](https://github.com/likyoo/BAN/assets/102707449/19a54f44-6406-4419-9704-64e3abaca7f6)

**Comment by likyoo** [comment]
是的，Landsat-CD需要预先进行一些数据转换的~  另外没有划分训练验证测试集

**Comment by wangqingl** [comment]
> 是的，Landsat-CD需要预先进行一些数据转换的~ 另外没有划分训练验证测试集

哦哦好的，谢谢您的回复

**Comment by wangqingl** [comment]
> 是的，Landsat-CD需要预先进行一些数据转换的~ 另外没有划分训练验证测试集

您好，李老师我还想问一个问题，我之前有使用您的open-cd训练过我的数据集，如果换成多类别的话，是不是只需要修改代码中的num_classes的数量就可以了
![image](https://github.com/likyoo/BAN/assets/102707449/4b65f349-952e-477e-b9c5-4efcb8fe412a)

**Comment by likyoo** [comment]
Landsat-CD我们把它转换成了像BANDON, SECOND的形式，使用语义变化检测的形式去做的。你可以参考opencd和BAN中这两种数据下模型的构造。

**Comment by wangqingl** [comment]
> Landsat-CD我们把它转换成了像BANDON, SECOND的形式，使用语义变化检测的形式去做的。你可以参考opencd和BAN中这两种数据下模型的构造。

好的，谢谢您
